### ISSUE TITLE
Unable to download JSON file properly

### ISSUE THREAD

**Issue by zachcoss** [rndme/download#100]
When I pass a JSON object and application/json mime type, I get a file that only contains the text **[object Object]**. Can someone confirm? I parsed the JSON and the object displays properly in the console (Chrome) before being passed to the downloadjs function.

Thanks.

**Comment by chekoopa** [comment]
> The input can be a String, Blob, or Typed Array of data, or via a dataURL representing the file's data as base64 or url-encoded string

Do you serialize your object before passing it as an input? Like, `JSON.stringify`. You can't put just a plain JSON, it would be implicitly casted with `toString`.

**Comment by lemanschik** [comment]
see: https://github.com/rndme/download/pull/117/files

Closed by: 
- #117
- #118

**Comment by rndme** [comment]
Yes, there's no single  way to stringify all objects, so we don't try.
