### ISSUE TITLE
PDF download

### ISSUE THREAD

**Issue by asimnzr** [rndme/download#18]
Hi,

I have few PDFs available on a URL, and I want to allow user to download them. I tried passing PDF as URL, but it did't work.

In example available on http://pagedemos.com/yvvmxbjrwq7u/2 , I replaced code for image download from: 
download( "/diff6.png" ); 
to
download( "www.example.com/diff6.pdf" );

but it did't work. Do we need to do any changes for PDF to get downloaded successfully?

Thanks.

**Comment by rndme** [comment]
you need to use a full URL, starting with "http", and you need to point to a file on the same server as the page, or use CORS headers when serving the PDF.
