### ISSUE TITLE
Is there any success and error event/callback?

### ISSUE THREAD

**Issue by myhirra** [rndme/download#23]

**Comment by rndme** [comment]
no, the browser doesn't allow any feedback as to the user's action.

**Comment by phuze** [comment]
I don't know the state of javascript/browser standards in 2016, but I can confirm this is possible at least as of today. I'm not knocking the author's work by any means, but a lack of a callback makes this package pretty tough to work with.

For anyone reading this issue, I recommend checking out [js-file-downloader](https://github.com/AleeeKoi/js-file-downloader) which provides similar functionality, along with callbacks.
