### ISSUE TITLE
Conflicting information regarding software license

### ISSUE THREAD

**Issue by jeremykohn** [rndme/download#34]
Is download.js licensed under [MIT](https://github.com/rndme/download/blob/7ea84e9648258d2ef9b452ed2f37d746cfcd6d46/bower.json), [Apache](https://github.com/rndme/download/blob/7ea84e9648258d2ef9b452ed2f37d746cfcd6d46/LICENSE), [CC-BY 4.0](https://github.com/rndme/download/blob/0887777e9f318bf4a4d42b8f1ce4b500cfd20189/package.json), or [CCBY2](https://github.com/rndme/download/blob/master/download.js)?

**Comment by rndme** [comment]
yikes, lol. I should get them all on the same page. Any pref before i unify?

**Comment by jeremykohn** [comment]
I like MIT.

**Comment by rndme** [comment]
mit all around, thanks for the suggestion.
