### ISSUE TITLE
Access-Control-Allow-Origin issue

### ISSUE THREAD

**Issue by pengfu** [rndme/download#35]
When I used it in my project ,I got an issue as the picture says.
![image](https://cloud.githubusercontent.com/assets/7261281/17358900/d1e087f2-5996-11e6-9722-613072f47f0d.png)

**Comment by rndme** [comment]
At some point about a year ago, maybe two, browsers stopped letting you use the `download` attrib on links to 3rd party domains. We can't use ajax either, so i'm afraid there is no client-side downloader solution for that. Enable cors, proxy the picture on your server, or instruct the user to right-click>save image...
