### ISSUE TITLE
Set Folder to download

### ISSUE THREAD

**Issue by vmontal** [rndme/download#37]
How can I set a specific folder to download the file, instead of the default folder "Downloads"?

**Comment by wbazant** [comment]
I think that this is impossible to decide on by the webpage, for security reasons - imagine you were able to tell the client to download anywhere on disk. All you can do is ask browsers to download things.

**Comment by rndme** [comment]
you can customize your browser settings to ask or auto-save to a custom folder. from JS, there's nothing we can do.
