### ISSUE TITLE
download file from URL

### ISSUE THREAD

**Issue by mgk89** [rndme/download#4]
Hi,

maybe it's a simple question, but I can't make it myself:

how has the function to look alike if I want to download an existing file?

like the filename is "image.jpg"?

thank you!

**Comment by rndme** [comment]
you can use bind() to force download() to act a callback to an ajax request that loads the existing file from a url on your server. with jQuery, that looks like:
`$.ajax({
        url: "/download.html",
        success: download.bind(true, "text/html", "dlAjaxCallback.html")
});`

with vanilla, it would be more like:
> var x=new XMLHttpRequest();
> x.open( "GET", "/download.html" , true);
> x.onload= download.bind(true, "text/html", "newLocalFileName.html");
> x.send();

I might add an option in the future to allow passing just an exiting url, and have download() do the ajax itself. sounds like that would be helpful, and i like it to be helpful. thanks for the interest!

**Comment by LaKing** [comment]
I couldt get either the vanilla, nor the JQuery suggestion to work.

It would be nice to download a file from an URL. I need a solution for an image file atm.

**Comment by jm4r7in** [comment]
@LaKing Have you found a solution ?

**Comment by LaKing** [comment]
In my javascript I use ...

```javascript
                if (window.ActiveXObject || "ActiveXObject" in window) {
                    // IE
                    var _window = window.open(fileURL, '_blank');
                    _window.document.title = fileName;
                    setTimeout(function() {
                        _window.document.execCommand('SaveAs', true, fileName);
                        _window.document.close();
                        _window.close();
                    }, 2000);

                } else {
                    // for non-IE
                    var save = document.createElement('a');
                    save.href = fileURL;
                    save.download = fileName;
                    var event = document.createEvent("MouseEvents");
                    event.initMouseEvent("click", true, false, window, 0, 0, 0, 0, 0, false, false, false, false, 0, null);
                    save.dispatchEvent(event);
                }
```

IE does not name the file for some reason.

**Comment by rndme** [comment]
Because of the different onload event arguments, Binary files can't use the built-in download callback feature, and apparently jQuery can't handle fetching binary files like images... I may make binary support a bug and fix it, but for now, you can use a tiny vanilla JS callback to get it done:

http://pagedemos.com/xmymv4cgcajx/3/

```
		var x=new XMLHttpRequest();
		x.open( "GET", "/diff6.png" , true);
		x.responseType = 'blob';
		x.onload= function(e){ download(e.target.response, "icon.png", "image/png" ) }
		x.send();
```

i'm going to close this issue since there's a way to accomplish the goal as-is, but i will strongly consider tweaking it to get binary ajax operational.
