### ISSUE TITLE
add download progress

### ISSUE THREAD

**Issue by veso266** [rndme/download#42]
Hi do you think you could add some download progerss in % in console.log as file downloads?

Thanks for Anwsering and Best Regards

**Comment by wbazant** [comment]
From what I can see, this would be hard with the current code - the code makes the downloadable content into one big object, puts it into a thing that the browser can see and tells the browser to download that thing.
I think it could be possible on new fancy browsers that use the WebRTC protocol- the WebTorrent project (https://webtorrent.io/  ) lets you download files as streams (its wiki says) and the demo page clearly shows me how much of a stream I have saved.
I'm not the maintainer (and myself will only enable the user to download tiny little text files) but what use case do you have, out of interest?

**Comment by rndme** [comment]
No, the browser does not make that info available to scripts.

**Comment by avalanche1** [comment]
Yeah, actually it does - https://usefulangle.com/post/68/javascript-ajax-download-file

**Comment by phuze** [comment]
I don't know the state of javascript/browser standards in 2016, but I can confirm this is possible at least as of today. I'm not knocking the author's work by any means, but a lack of a callback makes this package pretty tough to work with.

For anyone reading this issue, I recommend checking out [js-file-downloader](https://github.com/AleeeKoi/js-file-downloader) which provides similar functionality, along with callbacks and download progress.
