### ISSUE TITLE
Not all content types described by RFC 2045 are supported when using data urls

### ISSUE THREAD

**Issue by sa-linetco** [rndme/download#51]
As described by [RFC 2045](https://tools.ietf.org/html/rfc2045#section-5.1), all US-ASCII characters except SPACE, CTLs or tspecials are allowed in the content type.

The regular expression detecting data url usage only checks for words (`\w`) and dashes (`\-`).

How to reproduce:
Use a data url with a content type containing a dot (`.`) character.

For example:
`data:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;base64,<BASE64_ENCODED_DATA>`

**Comment by sa-linetco** [comment]
Apparently this was already fixed on github, but not in your release at http://danml.com/js/download.js

**Comment by rndme** [comment]
doh, thanks.
