### ISSUE TITLE
html5 A[download] trick is leaking click events

### ISSUE THREAD

**Issue by StevenLiekens** [rndme/download#54]
In the `saver()` function where an invisible anchor element is used to start the download, clicks are allowed to bubble up to the document root.

https://github.com/rndme/download/blob/31cf0fa096b2171c569e694e2416df2182449d01/download.js#L111

It would be great if the call to `anchor.click()` would stop clicks from propagating to the `body` element.

**Comment by StevenLiekens** [comment]
It's not immediately obvious why [line 109](https://github.com/rndme/download/blob/31cf0fa096b2171c569e694e2416df2182449d01/download.js#L109) and [line 112](https://github.com/rndme/download/blob/31cf0fa096b2171c569e694e2416df2182449d01/download.js#L112) are needed.

```js
// line 109
document.body.appendChild(anchor)

// line 112 (comes after anchor.click())
document.body.removeChild(anchor);
```

Are there browsers where the click doesn't work unless the anchor element is a child of the document's body? I tested in Chrome 59 where these lines are not needed.

If they are not needed then I suggest removing them. Otherwise, I suggest writing code to stop the `click` event from bubbling up to the `body` node.

**Comment by huy-nguyen** [comment]
It looks like the author has abandoned this repo and hasn't merged #55 after 3 months so I have forked the package and publish a version with the fix to npm: https://www.npmjs.com/package/downloadjs-next.

**Comment by pzheng64** [comment]
@huy-nguyen Did you have any chance for fixing Access-Control-Allow-Origin issue?
https://www.screencast.com/t/Wg0ieifd8C4

**Comment by StevenLiekens** [comment]
Hey Paul, create your own issue instead of commenting on mine. That has nothing to do with this.
