### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by kappuccino** [rndme/download#6]
Hello,
Your lib is very cool, you should publish it into the bower repository, so we will include easily in our project.

good job :beer:

**Comment by trothe** [comment]
+1

**Comment by vmartis** [comment]
+1

**Comment by jpstevens** [comment]
https://github.com/rndme/download/pull/11

**Comment by rndme** [comment]
thanks @jpstevens , added. I haven't gotten into bower yet, but the crowds have spoken, and i'd been meaning to get around to it.  `bower install downloadjs` now works as expected
