### ISSUE TITLE
error: download is not a function

### ISSUE THREAD

**Issue by dusadrian** [rndme/download#61]
I don't know how to describe it properly, and neither do I have a MRE.
But it seems that if the main function is called "download", that creates an error as described in the title.

I have renamed your function to something else (e.g. "downloadit") and then it worked.

No idea what might be triggering this error (I am using OS X version 10.9.5 and Chrome Version 64.0.3282.167), but I hope this might be of help somehow.

**Comment by arispati** [comment]
I've the same issue, using NPM to install downloadjs. 

```javascript
// Downloadjs
window.download = require("downloadjs")(data, strFileName, strMimeType);
```
end the result is
```
Uncaught (in promise) ReferenceError: download is not defined
```

**Comment by dusadrian** [comment]
Actually, that was my bad. I had another object called "download" in the global space (that I had forgotten about, and that cased the error in my case. Which explains why it worked when I renamed the function. Sorry for the noise, great library.
