### ISSUE TITLE
How is the message to download file appear

### ISSUE THREAD

**Issue by sarahbenjamin** [rndme/download#64]
I have been working with this library for last week now. In the beginning the file download message was coming at the bottom of the browser like this 
![image5](https://user-images.githubusercontent.com/38328456/39835309-a33cfa0e-5384-11e8-85a0-c5a75e8355b3.png)

I have seen it change to opening a save as window
![image4](https://user-images.githubusercontent.com/38328456/39835341-b00f3ddc-5384-11e8-86b9-986950c9e317.png)

and Today it just opens the file in jpeg, doesn't give a window message or show the file download bottom of the file, just simply opens it in photos,

Do we know what drives that behavior?

Thanks

**Comment by rndme** [comment]
Looks like those are browser preferences being changed on you, either file type associations (technically MIME associations) or browser updates that changed a previous behavior.
