### ISSUE TITLE
MS Edge does not add extension

### ISSUE THREAD

**Issue by pavterenin** [rndme/download#75]
download(blob, fileName);
blob.type = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"

All browsers download the file with .xlsx extension, except Edge. Edge just downloads file with fileName without any extension.

**Comment by roberto-slopez** [comment]
This works for me:
```js
download( resp.responseBytes, 'file.xlsx', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');

**Comment by nuthinking** [comment]
I got a similar problem in Electron on Windows: https://github.com/rndme/download/issues/91

**Comment by fkm** [comment]
There's a compatibility note on MDN:
>  Edge 17 or older didn't follow the attributes' value to determine filename ([bug 7260192](https://developer.microsoft.com/microsoft-edge/platform/issues/7260192/)).

Does anyone have an idea for a workaround?

[EDIT] This works https://github.com/eligrey/FileSaver.js

**Comment by rndme** [comment]
Newer versions of edge should work just fine.
