### ISSUE TITLE
Downloadjs breaks PDF file

### ISSUE THREAD

**Issue by ashl1** [rndme/download#8]
The library breaks PDF file and produces invalid PDF which opens with blank pages.
PDF Example: http://partners.adobe.com/public/developer/en/xml/AdobeXMLFormsSamples.pdf

Code:
```
$.ajax({
        url: '/AdobeXMLFormsSamples.pdf',
        success: download.bind(true, "application/pdf", 'AdobeXMLFormsSamples.pdf'), 
        complete: function(){...}
    });
```

Tested on browsers:
* Chromium Linux Version 44.0.2403.61 (64-bit)
* Firefox Linux 38.0.5

**Comment by skibz** [comment]
@ashl1 this isn't a bug in the library, your code isn't giving the `download` function a data source.
the problem is here:
```javascript
success: download.bind(true, "application/pdf", 'AdobeXMLFormsSamples.pdf'),
```
it ought to be:
```javascript
complete: function(event, xhr, settings) {
    download(xhr.responseHTML, 'application/pdf', 'AdobeXMLFormsSamples.pdf');
}
```

**Comment by bhargav3** [comment]
@skibz It should be as below right?

```javascript
complete: function(event, xhr, settings) {
    download(xhr.responseHTML, 'AdobeXMLFormsSamples.pdf',  'application/pdf');
}
```

**Comment by skibz** [comment]
@bhargav3 
ah, yes, well-spotted. i mixed up the mimetype and file name arguments!

**Comment by bhargav3** [comment]
Hi @skibz I'm trying to do this for word and excel files but all I get is the string as it is in the file. Strangely PDFs are working. Any idea why this might be happening?

**Comment by rndme** [comment]
binary files are a problem for jQuery ajax. see my last post on https://github.com/rndme/download/issues/4 for a vanilla workaround. i'm getting a strong sense that there's a need to be able to simply feed download() a url, and i'll see what i can do about that...

**Comment by bhargav3** [comment]
@rndme I was able solve this problem by converting string to URI and passing it to Downloadjs like below,

```javascript
dataURItoBlob = function (dataURI) {
                    var byteString = atob(dataURI.split(',')[1]),
                            mimeString = dataURI.split(',')[0].split(':')[1].split(';')[0],
                            ab = new ArrayBuffer(byteString.length),
                            ia = new Uint8Array(ab);
                    for (var i = 0; i < byteString.length; i++) {
                        ia[i] = byteString.charCodeAt(i);
                    }
                    return new Blob([ab], {'type': mimeString});
                };

download(dataURItoBlob(stringData), filename, mimetype);
```
