### ISSUE TITLE
[Feature Request] Support for downloading multiple files preferably .zip file or (.tar) file

### ISSUE THREAD

**Issue by nateshmbhat** [rndme/download#81]

**Comment by ricardoee** [comment]
Surely this would be an implementation you would do yourself on the backend?

**Comment by lemanschik** [comment]
out of scope

**Comment by lemanschik** [comment]
see: https://github.com/rndme/download/pull/117/files

Closed by: 
- #117
- #118

**Comment by rndme** [comment]
While that could be handy for some, it would require breaking argument signature changes and massively bloat the smallish code size that we all love. I'm playing with a virtual filesystem idea, and downloading folders and multiple files could well be a part, I'll update this issue with a link if the project matures to a release worthy status.

**Comment by lemanschik** [comment]
@rndme you can join my project i launch https://opfs.zip

**Comment by lemanschik** [comment]
@rndme i also got cloud-fs.zip and a file explorer and tar zip support and a phar like format called .esar ecmascript archive opfs.zip will implement .esar support esar is a simple format contianing a stub and integrity framework.
