### ISSUE TITLE
Request for adding an filepath argument

### ISSUE THREAD

**Issue by KingYapster** [rndme/download#90]
Request for adding an FilePath argument like:

download(data, strFilePath, strFileName, strMimeType);

Eg: FilePath = "E:\Files\";    

So, when the file is downloaded, it is stored in the location which we passed in the FilePath variable.

**Comment by rndme** [comment]
Sadly, there is no way to do this using the browser mechanisms that download.js uses. You might look into the newer `showSaveFilePicker()`.
