### ISSUE TITLE
mimeType error

### ISSUE THREAD

**Issue by Gytha** [rndme/download#94]
- Parameters: only data
Issuess:
Access to XMLHttpRequest has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
`     download(data)   `

- Parameters: (data, strFileName) or (data, strFileName, strMimeType)
 Issuess:
It can be downloaded but cannot be opened
This file format does not appear to be supported
`    download(data, strFileName)    `
`    download(data, strFileName, strMimeType )    `

**Comment by jamiegalbreath** [comment]
I have the same issue

**Comment by rndme** [comment]
You need to be able to reach the url from within js. I'm not sure what mime type you are having trouble with, some are blocked for security by the browser, some by the OS. I would be happy to take a closer look if you provide more details and especially a short code snip to reproduce the issue.
