### ISSUE TITLE
能否返回下载完成

### ISSUE THREAD

**Issue by chatterzhao** [rndme/download#98]
就是知道下载完成还是没有，想对不同状态进行不同处理。
这个fork 版本到[4.2](https://github.com/igauch/download)更新，但是不支持 ISSUE，所以还是到这边来问一下

**Comment by chatterzhao** [comment]
哦，好像知道了，当download 函数返回 true 的时候才成功

**Comment by chatterzhao** [comment]
我 fork 了代码，中国的朋友可以去我那边看看，修改了README.md [https://github.com/chatterzhao/download](https://github.com/chatterzhao/download)

**Comment by wangbinxiang** [comment]
> function download(url, cb, error) {
  const xhr = Download(url);
  console.log(xhr);
  xhr.onprogress = event => {
    if (event.lengthComputable) {
      var loaded = parseInt((event.loaded / event.total) * 100);
      console.log(loaded);
      cb(loaded);
    }
  };
  xhr.onerror = () => {
    console.log(0);
    error();
  };
}

**Comment by rndme** [comment]
Sorry, I don't understand the issue here.
